language: go

go:
  - 1.16.x
  - 1.18.x
  - tip

before_install:
  - go get ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)