openapi: 2.0
info:
  title: Sample API (2.0)
  description: Why are you still using this anyway?
  version: 1.2.4
tags:
  - name: Management
    description: Manage your things
  - name: Operations
    description: Operate your things
host: quobix.com
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string
        '201':    # status code
          description: created!
          schema:
            type: array
            items:
              type: string